# Generated by Django 5.2.5 on 2026-01-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterion4', '0003_successratestipulatedperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentspassedwithbacklogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_entry', models.CharField(max_length=20)),
                ('n1_n2_n3_total', models.IntegerField()),
                ('passed_year_1', models.IntegerField(blank=True, null=True)),
                ('passed_year_2', models.IntegerField(blank=True, null=True)),
                ('passed_year_3', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='successratestipulatedperiod',
            name='year_of_entry',
            field=models.CharField(max_length=20),
        ),
    ]
