# Generated by Django 5.2.5 on 2026-01-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterion4', '0004_studentspassedwithbacklogs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolmentRatio4_1_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('sanctioned_intake', models.IntegerField()),
                ('first_year_admitted', models.IntegerField()),
                ('lateral_entry', models.IntegerField(default=0)),
                ('separate_division', models.IntegerField(default=0)),
                ('total_admitted', models.IntegerField(editable=False)),
                ('enrolment_ratio', models.FloatField(editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
