# Generated by Django 5.2.5 on 2026-01-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterion4', '0005_enrolmentratio4_1_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolmentratio4_1_1',
            old_name='lateral_entry',
            new_name='N',
        ),
        migrations.RenameField(
            model_name='enrolmentratio4_1_1',
            old_name='separate_division',
            new_name='N1',
        ),
        migrations.RemoveField(
            model_name='enrolmentratio4_1_1',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='enrolmentratio4_1_1',
            name='enrolment_ratio',
        ),
        migrations.RemoveField(
            model_name='enrolmentratio4_1_1',
            name='first_year_admitted',
        ),
        migrations.RemoveField(
            model_name='enrolmentratio4_1_1',
            name='sanctioned_intake',
        ),
        migrations.RemoveField(
            model_name='enrolmentratio4_1_1',
            name='total_admitted',
        ),
        migrations.RemoveField(
            model_name='enrolmentratio4_1_1',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='enrolmentratio4_1_1',
            name='N1_m1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrolmentratio4_1_1',
            name='N1_m2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrolmentratio4_1_1',
            name='N2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrolmentratio4_1_1',
            name='N2_m1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrolmentratio4_1_1',
            name='N2_m2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrolmentratio4_1_1',
            name='N_m1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrolmentratio4_1_1',
            name='N_m2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrolmentratio4_1_1',
            name='year_label',
            field=models.CharField(default='CAY (2023-24)', max_length=50),
        ),
    ]
