# Generated by Django 5.2.5 on 2026-01-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterion4', '0006_rename_lateral_entry_enrolmentratio4_1_1_n_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolmentRatioMarksOnly4_1_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_90', models.IntegerField(default=20)),
                ('marks_80', models.IntegerField(default=18)),
                ('marks_70', models.IntegerField(default=16)),
                ('marks_60', models.IntegerField(default=12)),
                ('marks_50', models.IntegerField(default=8)),
                ('marks_below_50', models.IntegerField(default=0)),
            ],
        ),
    ]
