# Generated by Django 5.2.5 on 2026-02-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterion4', '0007_enrolmentratiomarksonly4_1_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementandHigherStudies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(default='CAY (2023-24)', max_length=50)),
                ('N', models.IntegerField(default=0)),
                ('X', models.IntegerField(default=0)),
                ('Y', models.IntegerField(default=0)),
                ('Z', models.IntegerField(default=0)),
                ('N_m1', models.IntegerField(default=0)),
                ('X_m1', models.IntegerField(default=0)),
                ('Y_m1', models.IntegerField(default=0)),
                ('Z_m1', models.IntegerField(default=0)),
                ('N_m2', models.IntegerField(default=0)),
                ('X_m2', models.IntegerField(default=0)),
                ('Y_m2', models.IntegerField(default=0)),
                ('Z_m2', models.IntegerField(default=0)),
            ],
        ),
    ]
