# Generated by Django 5.2.5 on 2026-02-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterion4', '0008_placementandhigherstudies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementandhigherstudies',
            name='N_m1',
        ),
        migrations.RemoveField(
            model_name='placementandhigherstudies',
            name='N_m2',
        ),
        migrations.RemoveField(
            model_name='placementandhigherstudies',
            name='X_m1',
        ),
        migrations.RemoveField(
            model_name='placementandhigherstudies',
            name='X_m2',
        ),
        migrations.RemoveField(
            model_name='placementandhigherstudies',
            name='Y_m1',
        ),
        migrations.RemoveField(
            model_name='placementandhigherstudies',
            name='Y_m2',
        ),
        migrations.RemoveField(
            model_name='placementandhigherstudies',
            name='Z_m1',
        ),
        migrations.RemoveField(
            model_name='placementandhigherstudies',
            name='Z_m2',
        ),
        migrations.AlterField(
            model_name='placementandhigherstudies',
            name='year_label',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
