# Generated by Django 5.2.5 on 2026-02-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterion4', '0009_remove_placementandhigherstudies_n_m1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(max_length=50, unique=True)),
                ('X', models.FloatField(default=0)),
                ('Y', models.IntegerField(default=0)),
                ('Z', models.IntegerField(default=0)),
            ],
        ),
    ]
