# Generated by Django 5.2.5 on 2026-02-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterion4', '0010_academicperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(max_length=20, unique=True)),
                ('X', models.IntegerField(default=0)),
                ('Y', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SuccessRateWithBacklogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(max_length=20, unique=True)),
                ('X', models.IntegerField(default=0)),
                ('Y', models.IntegerField(default=0)),
            ],
        ),
    ]
